#[macro_use]
extern crate tokio_trace;
// Tests that macros work across various invocation syntax.
//
// These are quite repetitive, and _could_ be generated by a macro. However,
// they're compile-time tests, so I want to get line numbers etc out of
// failures, and producing them with a macro would muddy the waters a bit.

#[test]
fn event() {
    event!(tokio_trace::Level::DEBUG, foo = 3, bar = 2, baz = false);
    event!(tokio_trace::Level::DEBUG, "foo");
    event!(tokio_trace::Level::DEBUG, "foo: {}", 3);
    event!(tokio_trace::Level::DEBUG, { foo = 3, bar = 80 }, "baz");
    event!(tokio_trace::Level::DEBUG, { foo = 2, bar = 79 }, "baz {:?}", true);
    event!(tokio_trace::Level::DEBUG, { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    event!(target: "foo_events", tokio_trace::Level::DEBUG, foo = 3, bar = 2, baz = false);
    event!(target: "foo_events", tokio_trace::Level::DEBUG, "foo");
    event!(target: "foo_events", tokio_trace::Level::DEBUG, "foo: {}", 3);
    event!(target: "foo_events", tokio_trace::Level::DEBUG, { foo = 3, bar = 80 }, "baz");
    event!(target: "foo_events", tokio_trace::Level::DEBUG, { foo = 2, bar = 79 }, "baz {:?}", true);
    event!(target: "foo_events", tokio_trace::Level::DEBUG, { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
}

#[test]
fn trace() {
    trace!(foo = 3, bar = 2, baz = false);
    trace!("foo");
    trace!("foo: {}", 3);
    trace!({ foo = 3, bar = 80 }, "baz");
    trace!({ foo = 2, bar = 79 }, "baz {:?}", true);
    trace!({ foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    trace!(target: "foo_events", foo = 3, bar = 2, baz = false);
    trace!(target: "foo_events", "foo");
    trace!(target: "foo_events", "foo: {}", 3);
    trace!(target: "foo_events", { foo = 3, bar = 80 }, "baz");
    trace!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}", true);
    trace!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
}

#[test]
fn debug() {
    debug!(foo = 3, bar = 2, baz = false);
    debug!("foo");
    debug!("foo: {}", 3);
    debug!({ foo = 3, bar = 80 }, "baz");
    debug!({ foo = 2, bar = 79 }, "baz {:?}", true);
    debug!({ foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    debug!(target: "foo_events", foo = 3, bar = 2, baz = false);
    debug!(target: "foo_events", "foo");
    debug!(target: "foo_events", "foo: {}", 3);
    debug!(target: "foo_events", { foo = 3, bar = 80 }, "baz");
    debug!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}", true);
    debug!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    debug!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
}

#[test]
fn info() {
    info!(foo = 3, bar = 2, baz = false);
    info!("foo");
    info!("foo: {}", 3);
    info!({ foo = 3, bar = 80 }, "baz");
    info!({ foo = 2, bar = 79 }, "baz {:?}", true);
    info!({ foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    info!(target: "foo_events", foo = 3, bar = 2, baz = false);
    info!(target: "foo_events", "foo");
    info!(target: "foo_events", "foo: {}", 3);
    info!(target: "foo_events", { foo = 3, bar = 80 }, "baz");
    info!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}", true);
    info!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    info!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
}

#[test]
fn warn() {
    warn!(foo = 3, bar = 2, baz = false);
    warn!("foo");
    warn!("foo: {}", 3);
    warn!({ foo = 3, bar = 80 }, "baz");
    warn!({ foo = 2, bar = 79 }, "baz {:?}", true);
    warn!({ foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    warn!(target: "foo_events", foo = 3, bar = 2, baz = false);
    warn!(target: "foo_events", "foo");
    warn!(target: "foo_events", "foo: {}", 3);
    warn!(target: "foo_events", { foo = 3, bar = 80 }, "baz");
    warn!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}", true);
    warn!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);

}

#[test]
fn error() {
    error!(foo = 3, bar = 2, baz = false);
    error!("foo");
    error!("foo: {}", 3);
    error!({ foo = 3, bar = 80 }, "baz");
    error!({ foo = 2, bar = 79 }, "baz {:?}", true);
    error!({ foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
    error!(target: "foo_events", foo = 3, bar = 2, baz = false);
    error!(target: "foo_events", "foo");
    error!(target: "foo_events", "foo: {}", 3);
    error!(target: "foo_events", { foo = 3, bar = 80 }, "baz");
    error!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}", true);
    error!(target: "foo_events", { foo = 2, bar = 79 }, "baz {:?}, {quux}", true, quux = false);
}
